services:
  - type: web
    name: django-web-colegio-simple
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py makemigrations sisacademico
      python manage.py migrate --noinput
      gunicorn colegio_simple.wsgi:application


