services:
  - type: web
    name: django-web-colegio-simple
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn colegio_simple.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: colegio_simple.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: tu_clave_secreta_aqui
      - key: DEBUG
        value: 'False'

