services:
  - type: web
    name: django-web-colegio-simple
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput --settings=colegio_simple.settings
      python manage.py migrate --noinput --settings=colegio_simple.settings
      python manage.py collectstatic --noinput --settings=colegio_simple.settings
    startCommand: gunicorn colegio_simple.wsgi:application

