services:
  - type: web
    name: django-web-colegio-simple
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn colegio_simple.wsgi:application

